#!/bin/bash

key="${1}"
timestamp="${2:-$(date +%s)}"
key_hex=$(echo -n "${key}" | base32 -d | xxd -p | xargs | tr -d ' ')
counter=$(printf %016x "$((timestamp / 30))")
hmac=$(echo -n "${counter}" | xxd -r -p | openssl dgst -sha1 -mac hmac -macopt hexkey:"${key_hex}" | awk '{print $2}')
offset=$((0x${hmac:39:1}))
truncated=${hmac:2*offset:8}
otp=$((0x${truncated} & 0x7fffffff))
printf "%06d\n" $((otp % 1000000))
